name: TuffX
version: 1.2.0
main: tf.tuff.TuffX
author: Potato
api-version: 1.18
depend: [ViaVersion, ViaBackwards]

commands:
  tuffx:
    description: Base command for the TuffX plugin.
    usage: /<command> mute
    permission: tuffx.mute
    aliases: [tx]

permissions:
  tuffx.mute:
    description: Allows a user to mute/unmute the TuffX console output.
    default: op